name: syntheticdatagen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - optuna
  - ipykernel
  - torchmetrics
  - scikit-learn
  - einops
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch>=2.7.0
      - torchvision
      - torchaudio
      - ray[air]
      - transformers
      - datasets